### ISSUE TITLE
Task conflict

### ISSUE THREAD

**Issue by TiboLR34** [ItsClemi/ews-managed-api#11]
Hi,

Thanks for the job you made.
Using vs community 2022 (latest release) I get conflict errors for Task but not Task<>
I've been able to workaround by aliasing ATP to Système.threading.task (ie ATP.Task Main(...)).
Am I doing somerhing wrong ? Why using Task keyword in this library? I haven't expérienced this issue in older assemblies

**Comment by Mertsch** [comment]
There is an Exchange Task object, which handles tasks inside of Exchange and has nothing to do with the .NET Task object.

You must explicitly reference `System.Threading.Task` or NOT use the namespace `Microsoft.Exchange.WebServices.Data` see https://github.com/ItsClemi/ews-managed-api/blob/ad1f1b7d80fd75dd59dce792b08daec59170cc17/src/Exchange.WebServices.NETCore/Core/ServiceObjects/Items/Task.cs#L36

**Comment by TiboLR34** [comment]
Thanks
I guess they kept it for legacy reasons as it became a conflict with asynchronous c# programming.
I'll use an alias for System.Threading.Task as I use it less often.

**Comment by ItsClemi** [comment]
Hi, thanks for reaching out. 
As @Mertsch already mentioned, this is a limitation of the API itself and the only workaround is using aliases or the full namespace qualifier.
