### ISSUE TITLE
ArgumentOutOfRangeException in AutodiscoverService

### ISSUE THREAD

**Issue by jensschmidbauer** [ItsClemi/ews-managed-api#18]
Hi, I'm just migrating from Microsoft.Exchange.WebServices.NETStandard to Exchange.WebServices.NETCore. Unfortunately, there's an Exception in AutoDiscoverService.PrepareHttpClient when setting the Timeout of the newly created HttpClient.

minimal code to reproduce (replace "***"):

```cs
const string server = "***";
const string mailAddress = "***";

AutodiscoverService service = new()
{
    Url = new Uri($"https://{server}/autodiscover/autodiscover.svc")
};

Console.WriteLine(service.Timeout); // 0

await service.GetUserSettings(mailAddress, UserSettingName.ExternalEwsUrl); // ArgumentOutOfRangeException

```

System.ArgumentOutOfRangeException: "value ('00:00:00') must be greater than '00:00:00'. 

 System.ArgumentOutOfRangeException.ThrowIfLessThanOrEqual[T](T value, T other, String paramName)
 System.ArgumentOutOfRangeException.ThrowLessEqual[T](T value, T other, String paramName)
 System.Net.Http.HttpClient.set_Timeout(TimeSpan value)
 Microsoft.Exchange.WebServices.Autodiscover.AutodiscoverService.PrepareHttpClient()
 Microsoft.Exchange.WebServices.Autodiscover.AutodiscoverRequest.<InternalExecute>d__3.MoveNext()
 Microsoft.Exchange.WebServices.Autodiscover.GetUserSettingsRequest.<Execute>d__4.MoveNext()
 Microsoft.Exchange.WebServices.Autodiscover.AutodiscoverService.<InternalGetUserSettings>d__36.MoveNext()
 Microsoft.Exchange.WebServices.Autodiscover.AutodiscoverService.<GetSettings>d__35`2.MoveNext()
 Microsoft.Exchange.WebServices.Autodiscover.AutodiscoverService.<InternalGetSoapUserSettings>d__33.MoveNext()
 Microsoft.Exchange.WebServices.Autodiscover.AutodiscoverService.<GetUserSettings>d__65.MoveNext()

Timeout always returns 0 (wenn set to full seconds).

ExchangeServiceBase.Timeout_get should return _httpClient.Timout.TotalMilliseconds (instead of .Milliseconds),
and for that the property type has to be double.

Would be great if you could fix this.
Thanks in advance.

**Comment by ItsClemi** [comment]
Hi,
thanks for reporting this issue! 

I've applied the changes you suggested in 2.1.2, but I kept the integer type on the property to preserve API compatibility (for now).

Thanks!
